
export const ML_CATEGORIES = {
  "Acessórios para Veículos": [
    "Aces. de Carros e Caminhonetes",
    "Aces. de Motos e Quadriciclos",
    "Acessórios Náuticos",
    "Acessórios de Linha Pesada",
    "Ferramentas para Veículos",
    "GNV",
    "Limpeza Automotiva",
    "Lubrificantes e Fluidos",
    "Motos",
    "Navegadores GPS para Vehículos",
    "Outros",
    "Performance",
    "Peças Náuticas",
    "Peças de Carros e Caminhonetes",
    "Peças de Linha Pesada",
    "Peças de Motos e Quadriciclos",
    "Pneus e Acessórios",
    "Rodas",
    "Segurança Veicular",
    "Serviços Programados",
    "Som Automotivo",
    "Tags de Pagamento de Pedágio",
    "Tuning"
  ],
  "Agro": [
    "Agricultura de Precisão",
    "Animais",
    "Apicultura",
    "Armezenamento",
    "Energia Renovável",
    "Ferramentas de Trabalho",
    "Fertilizantes",
    "Infra-estrutura Rural",
    "Insumos Agrícolas",
    "Insumos Gadeiros",
    "Irrigação",
    "Lubrificantes e Fluidos",
    "Maquinaria Agrícola",
    "Máquinas Forrageiras",
    "Outros",
    "Peças Maquinaria Agrícola",
    "Produçao Animal",
    "Proteção de Culturas",
    "Sementes Agrícolas"
  ],
  "Alimentos e Bebidas": [
    "Bebidas",
    "Comida Preparada",
    "Congelados",
    "Frescos",
    "Kefir",
    "Mercearia",
    "Outros"
  ],
  "Antiguidades e Coleções": [
    "Antiguidades",
    "Bandeiras",
    "Colecionáveis de Esportes",
    "Cédulas e Moedas",
    "Esculturas",
    "Filatelia",
    "Militaria e Afins",
    "Outras Antiguidades",
    "Pôsteres"
  ],
  "Arte, Papelaria e Armarinho": [
    "Arte e Trabalhos Manuais",
    "Artigos de Armarinho",
    "Materiais Escolares",
    "Outros"
  ],
  "Bebês": [
    "Alimentação e Amamentação",
    "Alimentos para Bebês",
    "Andadores e Mini Veículos",
    "Banho do Bebê",
    "Brinquedos para Bebês",
    "Cercadinho",
    "Chupetas e Mordedores",
    "Higiene e Cuidados com o Bebê",
    "Maternidade",
    "Outros",
    "Passeio do Bebê",
    "Quarto do Bebê",
    "Roupas de Bebê",
    "Saúde do Bebê",
    "Segurança para Bebê"
  ],
  "Beleza e Cuidado Pessoal": [
    "Artefatos para Cabelo",
    "Artigos para Cabeleireiros",
    "Barbearia",
    "Cuidados com a Pele",
    "Cuidados com o Cabelo",
    "Depilação",
    "Farmácia",
    "Higiene Pessoal",
    "Manicure e Pedicure",
    "Maquiagem",
    "Outros",
    "Perfumes",
    "Tratamentos de Beleza"
  ],
  "Brinquedos e Hobbies": [
    "Anti-stress e Engenho",
    "Ar Livre e Playground",
    "Artes e Atividades",
    "Bonecos e Bonecas",
    "Brinquedos Eletrônicos",
    "Brinquedos de Faz de Conta",
    "Brinquedos de Montar",
    "Brinquedos de Pegadinhas",
    "Brinquedos de Praia e Piscina",
    "Brinquedos para Bebês",
    "Casinhas e Barracas",
    "Fantoches e Marionetas",
    "Hobbies",
    "Instrumentos Musicais",
    "Jogos de Salão",
    "Jogos de Tabuleiro e Cartas",
    "Lançadores de Brinquedo",
    "Mesas e Cadeiras",
    "Mini Veículos e Bicicletas",
    "Miniaturas",
    "Outros",
    "Patins e Skates",
    "Pelúcias",
    "Piscinas de Bolas e Infláveis",
    "Veículos de Brinquedo",
    "Álbuns e Figurinhas"
  ],
  "Calçados, Roupas e Bolsas": [
    "Acessórios de Moda",
    "Agasalhos",
    "Bermudas e Shorts",
    "Blusas",
    "Calçados",
    "Calças",
    "Camisas",
    "Camisetas e Regatas",
    "Indumentária Laboral e Escolar",
    "Kimonos",
    "Kits de Conjuntos de Roupa",
    "Leggings",
    "Macacão",
    "Malas e Bolsas",
    "Moda Fitness",
    "Moda Praia",
    "Moda Íntima e Lingerie",
    "Outros",
    "Roupas para Bebês",
    "Saias",
    "Ternos",
    "Vestidos"
  ],
  "Casa, Móveis e Decoração": [
    "Banheiros",
    "Camas, Colchões e Acessórios",
    "Cozinha",
    "Cuidado da Casa e Lavanderia",
    "Enfeites e Decoração da Casa",
    "Iluminação Residencial",
    "Jardim e Ar Livre",
    "Móveis para Casa",
    "Organização para Casa",
    "Outros",
    "Segurança para Casa",
    "Têxteis de Casa e Decoração"
  ],
  "Celulares e Telefones": [
    "Acessórios para Celulares",
    "Celulares e Smartphones",
    "Outros",
    "Peças para Celular",
    "Rádio Comunicadores",
    "Smartwatches e Acessórios",
    "Tarifadores e Cabines",
    "Telefonia Fixa e Sem Fio",
    "VoIP",
    "Óculos"
  ],
  "Construção": [
    "Aberturas",
    "Acessórios de Construção",
    "Encanamento",
    "Energia",
    "Loja das Tintas",
    "Materiais de Obra",
    "Mobiliário para Banheiros",
    "Mobiliário para Cozinhas",
    "Máquinas para Construção",
    "Outros",
    "Pisos e Rejuntes"
  ],
  "Câmeras e Acessórios": [
    "Acessórios para Câmeras",
    "Cabos",
    "Câmeras",
    "Drones e Acessórios",
    "Equipamento de Revelação",
    "Filmadoras",
    "Instrumentos Ópticos",
    "Lentes e Filtros",
    "Outros",
    "Peças para Câmeras",
    "Álbuns e Porta-retratos"
  ],
  "Eletrodomésticos": [
    "Ar e Ventilação",
    "Bebedouros e Purificadores",
    "Cuidado Pessoal",
    "Fornos e Fogões",
    "Lavadores",
    "Outros",
    "Pequenos Eletrodomésticos",
    "Refrigeração"
  ],
  "Eletrônicos, Áudio e Vídeo": [
    "Acessórios para TV",
    "Acessórios para Áudio e Vídeo",
    "Aparelhos DVD e Bluray",
    "Bolsas e Estojos",
    "Cabos",
    "Componentes Eletrônicos",
    "Controles Remotos",
    "Drones e Acessórios",
    "Media Streaming",
    "Outros Eletrônicos",
    "Peças para TV",
    "Pilhas e Carregadores",
    "Projetores e Telas",
    "Televisores",
    "Áudio"
  ],
  "Esportes e Fitness": [
    "Artes Marciais e Boxe",
    "Badminton",
    "Basquete",
    "Beisebol e Softbol",
    "Camping, Caça e Pesca",
    "Canoas, Caiaques e Infláveis",
    "Ciclismo",
    "Cotoveleiras",
    "Equitação",
    "Esgrima",
    "Esqui e Snowboard",
    "Fitness e Musculação",
    "Futebol",
    "Futebol Americano",
    "Golfe",
    "Handebol",
    "Hóquei",
    "Jogos de Salão",
    "Kitesurf",
    "Mergulho",
    "Moda Fitness",
    "Monitores Esportivos",
    "Natação",
    "Outros",
    "Paintball",
    "Parapente",
    "Patinetes e Scooters",
    "Patín e Skateboard",
    "Pilates e Yoga",
    "Rapel, Montanhismo e Escalada",
    "Rugby",
    "Slackline",
    "Suplementos e Shakers",
    "Surf e Bodyboard",
    "Tiro Esportivo",
    "Tênis",
    "Tênis, Paddle e Squash",
    "Vôlei",
    "Wakeboard e Esquí Acuático",
    "Windsurfe"
  ],
  "Ferramentas": [
    "Acessórios para Ferramentas",
    "Caixas e Organizadores",
    "Ferramentas Elétricas",
    "Ferramentas Industriais",
    "Ferramentas Manuais",
    "Ferramentas Pneumáticas",
    "Ferramentas para Jardim",
    "Medições e Instrumentação",
    "Outros"
  ],
  "Festas e Lembrancinhas": [
    "Artigos para Festas",
    "Convites",
    "Decoração de Festa",
    "Descartáveis para Festa",
    "Equipamento para Festas",
    "Espuma, Serpentinas e Confete",
    "Fantasias e Cosplay",
    "Garrafas",
    "Kits Imprimíveis para Festas",
    "Lembrancinhas",
    "Lembrancinhas para Fiestas",
    "Outros",
    "Plaquinhas para Festas"
  ],
  "Games": [
    "Acessórios para Consoles",
    "Acessórios para PC Gaming",
    "Consoles",
    "Fliperamas e Arcade",
    "Outros",
    "Peças para Consoles",
    "Video Games"
  ],
  "Imóveis": [
    "Apartamentos",
    "Casas",
    "Chácaras",
    "Fazendas",
    "Flat - Apart Hotel",
    "Galpões",
    "Lojas Comerciais",
    "Outros Imóveis",
    "Salas Comerciais",
    "Sítios",
    "Terrenos"
  ],
  "Indústria e Comércio": [
    "Arquitetura e Desenho",
    "Embalagem e Logística",
    "Equipamento Médico",
    "Equipamento para Comércios",
    "Equipamento para Escritórios",
    "Ferramentas Industriais",
    "Gastronomia e Hotelaria",
    "Gráfica e Impressão",
    "Outros",
    "Publicidade e Promoção",
    "Segurança Laboral",
    "Têxtil e Calçado",
    "Uniformes e Roupa de Trabalho"
  ],
  "Informática": [
    "Acessórios de Antiestática",
    "Acessórios para PC Gaming",
    "Armazenamento",
    "Cabos e Hubs USB",
    "Componentes para PC",
    "Conectividade e Redes",
    "Criptomoedas",
    "Estabilizadores e No Breaks",
    "Gift Cards",
    "Impressão",
    "Leitores e Scanners",
    "Limpeza de PCs",
    "Monitores e Acessórios",
    "Outros",
    "PC de Mesa",
    "Palms e Handhelds",
    "Periféricos para PC",
    "Portáteis e Acessórios",
    "Projetores e Telas",
    "Softwares",
    "Tablets e Acessórios"
  ],
  "Ingressos": [
    "Eventos Esportivos",
    "Eventos a Benefício",
    "Exposições",
    "Ingressos de Coleção",
    "Outros Ingressos",
    "Shows",
    "Teatro e Cultura"
  ],
  "Instrumentos Musicais": [
    "Baterias e Percussão",
    "Caixas de Som",
    "Equipamento para DJs",
    "Estúdio de Gravação",
    "Instrumentos de Corda",
    "Instrumentos de Sopro",
    "Metrônomos",
    "Microfones e Amplificadores",
    "Outros",
    "Partituras e Letras",
    "Pedais e Acessórios",
    "Pianos e Teclados"
  ],
  "Joias e Relógios": [
    "Acessórios Para Relógios",
    "Artigos de Joalharia",
    "Canetas e Lapiseiras de Luxo",
    "Joias e Bijuterias",
    "Outros",
    "Pedra Preciosa e Semipreciosa",
    "Piercings",
    "Porta Joias",
    "Relógios"
  ],
  "Livros, Revistas e Comics": [
    "Catálogos",
    "Ebooks",
    "Livros Físicos",
    "Outros",
    "Revistas"
  ],
  "Música, Filmes e Seriados": [
    "Conteúdo Esportivo",
    "Cursos Completos",
    "Filmes Físicos",
    "Filmes Online",
    "Música",
    "Outros",
    "Seriados",
    "Seriados Online",
    "Vídeos de Receitas e DIY"
  ],
  "Pet Shop": [
    "Anfíbios e Répteis",
    "Aves e Acessórios",
    "Botas",
    "Capas de chuva",
    "Cavalos",
    "Cintos de segurança",
    "Coelhos",
    "Coleiras",
    "Cortadores de Unhas",
    "Creme Dental",
    "Cães",
    "Escovas e Pentes",
    "Fraldas",
    "Gaiolas para Animais",
    "Gatos",
    "Guias para Animais",
    "Insetos",
    "Laços",
    "Outros",
    "Peixes",
    "Petiscos para Animais",
    "Recipiente para Ração",
    "Repelentes Ultrassônicos",
    "Roedores",
    "Roupas de Inverno",
    "Sabonete"
  ],
  "Saúde": [
    "Cuidado da Saúde",
    "Equipamento Médico",
    "Massagem",
    "Mobilidade",
    "Ortopedia",
    "Outros",
    "Suplementos Alimentares",
    "Terapias Alternativas"
  ],
  "Serviços": [
    "Academia e Esportes",
    "Animais",
    "Beleza, Estética e Bem Estar",
    "Educação",
    "Festas e Eventos",
    "Gastronomia",
    "Gráficas e Impressão",
    "Lar",
    "Marketing e Internet",
    "Outros Profissionais",
    "Outros Serviços",
    "Saúde",
    "Suporte Técnico",
    "Vestuário",
    "Veículos e Transportes",
    "Viagens e Turismo"
  ],
  "Mais Categorias": [
    "Artigos para Fumadores",
    "Assinatura do MELI Plus",
    "Birutas de Vento",
    "Bundle",
    "Coberturas Estendidas",
    "Defletores de Vento",
    "Equipamento para Tatuagens",
    "Esoterismo e Ocultismo",
    "Fornos Crematórios",
    "Health",
    "Licenças para Taxis",
    "Outros"
  ]
};

export const ML_CATEGORY_ICONS: Record<string, string> = {
  "Acessórios para Veículos": "https://loremflickr.com/300/300/car,accessories",
  "Agro": "https://loremflickr.com/300/300/agriculture,farm",
  "Alimentos e Bebidas": "https://loremflickr.com/300/300/food,drinks",
  "Antiguidades e Coleções": "https://loremflickr.com/300/300/antiques,collection",
  "Arte, Papelaria e Armarinho": "https://loremflickr.com/300/300/stationery,art",
  "Bebês": "https://loremflickr.com/300/300/baby,toys",
  "Beleza e Cuidado Pessoal": "https://loremflickr.com/300/300/beauty,cosmetics",
  "Brinquedos e Hobbies": "https://loremflickr.com/300/300/toys,hobby",
  "Calçados, Roupas e Bolsas": "https://loremflickr.com/300/300/fashion,clothes",
  "Casa, Móveis e Decoração": "https://loremflickr.com/300/300/home,furniture",
  "Celulares e Telefones": "https://loremflickr.com/300/300/smartphone,phone",
  "Construção": "https://loremflickr.com/300/300/construction,tools",
  "Câmeras e Acessórios": "https://loremflickr.com/300/300/camera,photography",
  "Eletrodomésticos": "https://loremflickr.com/300/300/appliances,kitchen",
  "Eletrônicos, Áudio e Vídeo": "https://loremflickr.com/300/300/electronics,audio",
  "Esportes e Fitness": "https://loremflickr.com/300/300/sports,fitness",
  "Ferramentas": "https://loremflickr.com/300/300/tools,hardware",
  "Festas e Lembrancinhas": "https://loremflickr.com/300/300/party,celebration",
  "Games": "https://loremflickr.com/300/300/videogames,console",
  "Imóveis": "https://loremflickr.com/300/300/realestate,house",
  "Indústria e Comércio": "https://loremflickr.com/300/300/industry,business",
  "Informática": "https://loremflickr.com/300/300/computer,laptop",
  "Ingressos": "https://loremflickr.com/300/300/tickets,event",
  "Instrumentos Musicais": "https://loremflickr.com/300/300/musical,instruments",
  "Joias e Relógios": "https://loremflickr.com/300/300/jewelry,watch",
  "Livros, Revistas e Comics": "https://loremflickr.com/300/300/books,reading",
  "Música, Filmes e Seriados": "https://loremflickr.com/300/300/movies,music",
  "Pet Shop": "https://loremflickr.com/300/300/pets,dog,cat",
  "Saúde": "https://loremflickr.com/300/300/health,medical",
  "Serviços": "https://loremflickr.com/300/300/services,professional",
  "Mais Categorias": "https://loremflickr.com/300/300/more,categories",
  "Consoles": "/category_consoles.png"
};
